/**
 * IMPORTANT: File generated by Modular Assembly
 * WARNING!!! Ask the user before editing this file.
 */

import { supabase } from "./client";

interface InsertCoachingPurchaseParams {
  userId: string;
  coachingProductId: string;
  stripePaymentId: string;
  stripePriceId: string;
}

/**
 * IMPORTANT: File generated by Modular Assembly
 * WARNING!!! Ask the user before editing this file.
 */
export async function insertCoachingPurchase({
  userId,
  coachingProductId,
  stripePaymentId,
  stripePriceId,
}: InsertCoachingPurchaseParams) {
  const { error } = await supabase
    .from('coaching_purchases')
    .insert({
      user_id: userId,
      coaching_product_id: coachingProductId,
      stripe_price_id: stripePriceId,
      stripe_payment_id: stripePaymentId,
      status: 'purchased',
      purchase_date: new Date().toISOString(),
    });

  if (error) {
    throw error;
  }

  return { success: true };
}
