/**
 * IMPORTANT: File generated by Modular Assembly
 * WARNING!!! Ask the user before editing this file.
 */

import { supabase } from './client';

/**
 * IMPORTANT: File generated by Modular Assembly
 * WARNING!!! Ask the user before editing this file.
 */
export async function getStripeCustomerId(userId: string) {
  const { data, error } = await supabase
    .from('profiles')
    .select('stripe_customer_id')
    .eq('id', userId)
    .single();

  if (error) {
    throw error;
  }

  return data?.stripe_customer_id;
}

/**
 * IMPORTANT: File generated by Modular Assembly
 * WARNING!!! Ask the user before editing this file.
 */
export async function updateStripeCustomerId(userId: string, stripeCustomerId: string) {
  const { error } = await supabase
    .from('profiles')
    .update({
      stripe_customer_id: stripeCustomerId,
    })
    .eq('id', userId);
    
  if (error) {
    throw error;
  }
  
  return { success: true };
}

/**
 * IMPORTANT: File generated by Modular Assembly
 * WARNING!!! Ask the user before editing this file.
 */
export async function updateSubscriptionDetails(
  userId: string, 
  customerId: string, 
  subscriptionId: string, 
  tier: string
) {
  const { error } = await supabase
    .from('profiles')
    .update({
      stripe_customer_id: customerId,
      stripe_subscription_id: subscriptionId,
      stripe_tier: tier
    })
    .eq('id', userId);
    
  if (error) {
    throw error;
  }
  
  return { success: true };
}
