/**
 * IMPORTANT: File generated by Modular Assembly
 * WARNING!!! Ask the user before editing this file.
 */

import { supabase } from '@/lib/modassembly/supabase/client';

interface CreateCoachingCheckoutParams {
  productId: string;
  priceId: string;
  successUrl: string;
  cancelUrl: string;
}

/**
 * IMPORTANT: File generated by Modular Assembly
 * WARNING!!! Ask the user before editing this file.
 */
export async function createCoachingCheckout({
  productId,
  priceId,
  successUrl,
  cancelUrl,
}: CreateCoachingCheckoutParams) {
  try {
    const { data: { session } } = await supabase.auth.getSession();
    if (!session?.access_token) {
      throw new Error('No authentication token found');
    }

    const response = await fetch('/api/stripe/create-coaching-checkout', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${session.access_token}`,
      },
      body: JSON.stringify({
        productId,
        priceId,
        successUrl,
        cancelUrl,
      }),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(errorData.error || 'Failed to create checkout session');
    }

    const { sessionId } = await response.json();
    return sessionId;
  } catch (error) {
    console.error('Error creating coaching checkout session:', error);
    throw error;
  }
}

export async function redirectToCheckout(sessionId: string) {
  const stripe = await import('./client').then(module => module.stripePromise);
  if (!stripe) {
    throw new Error('Stripe not initialized');
  }
  
  const { error } = await stripe.redirectToCheckout({ sessionId });
  if (error) {
    throw error;
  }
} 